add_newline = false

[character]
symbol = "➜"

[directory]
truncation_length = 0
truncate_to_repo = false

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
show_sync_count = true
